import type { NormalizedFinding, ScanSummary, Verdict } from "./types.js";
import { SEVERITY_ORDER, countBySeverity, locationOf, sortBySeverity } from "./findings.js";
import { isAdvisory, scoredFindings } from "./score.js";

/**
 * Renders a scan as Markdown, for pasting into a pull request, an issue, or an
 * editor's AI chat.
 *
 * Pure and deterministic, like the score: same report in, same bytes out. The
 * ordering and the separations mirror the web report exactly — verdict first,
 * then coverage, then scanner findings, then advisory — because two renderings
 * of the same scan disagreeing about what counts would be worse than having
 * only one.
 */

export interface MarkdownReport {
  repoUrl: string;
  commitSha: string | null;
  score: number;
  verdict: Verdict;
  summary: ScanSummary | null;
  failedScanners: string[];
  findings: NormalizedFinding[];
  generatedAt?: string;
}

const VERDICT_LINE: Record<Verdict, string> = {
  pass: "No blocking issues from the checks that ran.",
  review: "Real issues that are not immediately exploitable. Read them before shipping.",
  block: "At least one finding is severe enough to be exploited as-is.",
};

export function toMarkdown(report: MarkdownReport): string {
  const scanner = sortBySeverity(scoredFindings(report.findings));
  const advisory = sortBySeverity(report.findings.filter(isAdvisory));
  const counts = report.summary ?? countBySeverity(scanner);

  const out: string[] = [];

  out.push(`# VibeGuard report — ${slug(report.repoUrl)}`, "");
  out.push(`**${report.score}/100 · ${report.verdict.toUpperCase()}** — ${VERDICT_LINE[report.verdict]}`, "");

  const meta = [`Repository: ${report.repoUrl}`];
  if (report.commitSha) meta.push(`Commit: \`${report.commitSha.slice(0, 7)}\``);
  if (report.generatedAt) meta.push(`Scanned: ${report.generatedAt}`);
  out.push(meta.join(" · "), "");

  if (report.failedScanners.length > 0) {
    out.push(
      `> **Partial scan.** ${report.failedScanners.join(", ")} did not run, so this score was`,
      `> computed from fewer checks. Treat it as a floor, not a clean bill of health.`,
      "",
    );
  }

  out.push("## Severity", "");
  out.push("| Severity | Count |", "| --- | --- |");
  for (const severity of SEVERITY_ORDER) {
    out.push(`| ${severity} | ${counts[severity] ?? 0} |`);
  }
  out.push("");

  out.push(`## Findings (${scanner.length})`, "");
  if (scanner.length === 0) {
    out.push(
      "None of the scanners that ran reported an issue. That is not a proof of safety — it means",
      "these specific checks came back clean.",
      "",
    );
  } else {
    for (const [index, finding] of scanner.entries()) {
      out.push(...findingBlock(finding, index + 1));
    }
  }

  if (advisory.length > 0) {
    out.push(`## AI review (${advisory.length}) — advisory, not scored`, "");
    out.push(
      "Model observations about weaknesses a pattern-matching scanner cannot express. These do not",
      "affect the score and are not reproducible the way a scanner rule is — treat them as leads.",
      "",
    );
    for (const [index, finding] of advisory.entries()) {
      out.push(...findingBlock(finding, index + 1));
    }
  }

  out.push("---", "", "Generated by VibeGuard.");
  return out.join("\n");
}

function findingBlock(finding: NormalizedFinding, position: number): string[] {
  const block: string[] = [];
  block.push(`### ${position}. [${finding.severity.toUpperCase()}] ${finding.title}`, "");

  const facts = [`Detected by: \`${finding.source}\``, `Category: ${finding.category}`];
  const location = locationOf(finding);
  if (location) facts.unshift(`Location: \`${location}\``);
  block.push(facts.join(" · "), "");

  if (finding.snippet) {
    block.push("```", finding.snippet.trim(), "```", "");
  }
  if (finding.explanation) {
    block.push(`**Why it matters.** ${finding.explanation.trim()}`, "");
  }
  if (finding.recommendedFix) {
    block.push(`**Fix.** ${finding.recommendedFix.trim()}`, "");
  }
  return block;
}

/** `https://github.com/owner/repo` → `owner/repo`. */
function slug(repoUrl: string): string {
  return repoUrl.replace(/^https:\/\/github\.com\//i, "").replace(/\.git$/i, "");
}
